name: Build SunamoMathpix

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoMathpix
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMathpix/SunamoMathpix.csproj

    - name: Build
      run: dotnet build SunamoMathpix/SunamoMathpix.csproj --configuration Release --no-restore

  test:
    name: Test SunamoMathpix.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoMathpix.Tests/SunamoMathpix.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoMathpix.Tests/SunamoMathpix.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoMathpix.Tests/SunamoMathpix.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
